# abstract constants
from .PRIMES import PRIMES
from .MINIMAL_DURATION_OF_ONE_SOUND import MINIMAL_DURATION_OF_ONE_SOUND
from .ACTIVITY_RANGE import ACTIVITY_RANGE
from .FREQUENCY_RANGE import FREQUENCY_RANGE
from .RANDOM_SEED import RANDOM_SEED
from .BUILD_PATH import BUILD_PATH
from .LOUDSPEAKER_MONO_FILES_BUILD_PATH import LOUDSPEAKER_MONO_FILES_BUILD_PATH
from .LOUDSPEAKER_MONO_FILES_BUILD_PATH_RELATIVE import LOUDSPEAKER_MONO_FILES_BUILD_PATH_RELATIVE
from .LOUDSPEAKER_MONO_FILES_BUILD_PATH_ABSOLUTE import LOUDSPEAKER_MONO_FILES_BUILD_PATH_ABSOLUTE
from .MIX_PATH import MIX_PATH

# harmony definition
from .HARMONIES import HARMONIES
from .HARMONIES_IN_CORRECT_REGISTER import HARMONIES_IN_CORRECT_REGISTER

# loudspeaker & loudspeaker positions
from .LOUDSPEAKERS import LOUDSPEAKERS
from .RING_POSITION_TO_LOUDSPEAKER import RING_POSITION_TO_LOUDSPEAKER
from .OUTPUT_CHANNEL_TO_SPEAKER import OUTPUT_CHANNEL_TO_SPEAKER
from .PITCH_TO_LOUDSPEAKER_MAPPING import PITCH_TO_LOUDSPEAKER_MAPPING

# initialising Loudness converter
from .LOUDNESS_LEVEL_RANGE import LOUDNESS_LEVEL_RANGE
from .N_LOUDNESS_LEVELS import N_LOUDNESS_LEVELS
from .LOUDNESS_LEVELS import LOUDNESS_LEVELS
from .LOUDNESS_CONVERTER import LOUDNESS_CONVERTER

# duration / time per harmony -> transition between harmonies
from .TRANSITION_PHASES_FACTOR import TRANSITION_PHASES_FACTOR
from .TRANSITION_PHASES_EXPONENT import TRANSITION_PHASES_EXPONENT
from .TRANSITION_PHASES import TRANSITION_PHASES
from .MIN_N_PHASES_FOR_SUSTAIN import MIN_N_PHASES_FOR_SUSTAIN
from .MAX_N_MIN_PHASES_FOR_SUSTAIN import MAX_N_MIN_PHASES_FOR_SUSTAIN
from .GROUPS import GROUPS
from .DURATION import DURATION
from .ABSOLUTE_START_TIME_PER_GROUP import ABSOLUTE_START_TIME_PER_GROUP

# composed objects in time
from .NESTED_PARTIALS import NESTED_PARTIALS
